from __future__ import annotations

from alembic import op
import sqlalchemy as sa

revision = '293a600428e8'
down_revision = '0011_backups'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('last_visit', sa.Date(), nullable=True))
    op.add_column('partners', sa.Column('last_visit_type', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('last_project', sa.Text(), nullable=True))
    op.add_column('partners', sa.Column('last_project_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partners', 'last_project_type')
    op.drop_column('partners', 'last_project')
    op.drop_column('partners', 'last_visit_type')
    op.drop_column('partners', 'last_visit')
    # ### end Alembic commands ###
